# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IRLCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('longitude', models.IntegerField(default=0)),
                ('latitude', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('origin_city', models.CharField(max_length=150)),
                ('origin_state', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('origin_country', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='super',
            name='company_universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supers_related', to='supers.Universe'),
        ),
        migrations.AddField(
            model_name='super',
            name='irl_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supers_related', to='supers.IRLCity'),
        ),
    ]
