# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irlcity',
            name='province',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='super',
            name='identity',
            field=models.CharField(default='identity', max_length=300),
        ),
        migrations.AlterField(
            model_name='irlcity',
            name='name',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AlterField(
            model_name='super',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
