# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_auto_20160305_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='first_appearance',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
